seed: 1234

image_key: "image"
batch_size: 32
lr: 1.e-4
total_steps: 200000
warmup_steps: 0
save_interval: 20000
test_interval: 20000
viz_interval: 1000
log_interval: 100
data_path: "/tmp/metaworld_data_pretrain"

ema: 0.9999
optimizer: "adam"
lr_schedule: "constant"

image_size: 64
seq_len: 4
frame_skip: 4
ae_ckpt: "/tmp/viper/metaworld/metaworld_vqgan"

n_classes: 8
class_cond: true

model: "videogpt"
transformer:
  embed_dim: 256
  num_heads: 8
  num_layers: 8
  mlp_dim: 1024
  dropout: 0.0
  attention_dropout: 0.0

open_loop_ctx: 1
